import React, { useState, useCallback } from 'react';
import { Brain } from 'lucide-react';
import { TextInput } from './components/TextInput';
import { AnalysisResult as AnalysisResultComponent } from './components/AnalysisResult';
import { analyzeText, type AnalysisResult } from './utils/textAnalysis';

function App() {
  const [text, setText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);

  const handleTextChange = useCallback((newText: string) => {
    setText(newText);
    if (newText.length > 50) {
      setIsAnalyzing(true);
      // Simulate some processing time for better UX
      setTimeout(() => {
        setResult(analyzeText(newText));
        setIsAnalyzing(false);
      }, 500);
    } else {
      setResult(null);
    }
  }, []);

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 py-12">
        <div className="text-center mb-12">
          <div className="flex justify-center mb-4">
            <Brain className="h-12 w-12 text-blue-600" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            AI Text Detector
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Analyze text to determine if it might be generated by AI. This tool
            examines patterns, structure, and language characteristics.
          </p>
        </div>

        <div className="flex flex-col items-center gap-8">
          <TextInput
            text={text}
            onChange={handleTextChange}
            isAnalyzing={isAnalyzing}
          />

          {isAnalyzing && (
            <div className="animate-pulse text-gray-600">
              Analyzing text...
            </div>
          )}

          <AnalysisResultComponent result={result} />
        </div>
      </div>
      
      <div className='bg-black text-white text-center py-5 mt-12'>
      <p >Developed by : Mohammad Ehsan Nicksarisht</p>
        </div>
    </div>
  );
}

export default App;